language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
install: pip install --upgrade --requirement requirements.txt --requirement dev-requirements.txt
script:
  - isort --quiet --diff --recursive
  - isort --check-only --recursive
  - flake8
  - pytest --cov
