language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - 'pypy'
  - 'pypy-5.3.1'
install: pip install --upgrade --requirement dev-requirements.txt
script:
  - isort --quiet --diff --recursive
  - isort --check-only --recursive
  - flake8
  - pytest --cov
  - python setup.py check
  - check-manifest
