language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - 'pypy3.5'
  - 'pypy'
install:
  - pip install poetry
  - poetry install
script:
  - isort --quiet --diff --recursive
  - isort --check-only --recursive
  - flake8
  - pytest --cov
